apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-service
  template:
    metadata:
      labels:
        app: auction-service
        prometheus.io/scrape: "true"
        prometheus.io/port: "3002"
    spec:
      containers:
      - name: auction-service
        image: ung-dung-phan-tan-web-auction-auction-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        - name: MONGODB_URI
          value: "mongodb://mongodb-auction:27017/auction_db"
        - name: REDIS_URL
          value: "redis://:redis123@redis:6379"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"
        - name: PAYMENT_SERVICE_URL
          value: "http://payment-service:3006"
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: auction-service
spec:
  selector:
    app: auction-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auction-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auction-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
